coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "src/test/**/*"
  - "**/*.d.ts"
  - "**/*.config.*"
  - "**/types/**/*"
  - "src/vite-env.d.ts" 