import { AuditTrail } from './types';
import { StatusType } from '@/types/declarations';

// Generate mock audit logs
export const mockAuditLogs: AuditTrail[] = [
  {
    id: '1',
    date: new Date('2023-10-25T14:32:10'),
    userName: 'admin',
    userRole: 'Administrator',
    action: 'create',
    resourceName: 'Tax Credit',
    resourceId: 'TC-001',
    ipAddress: '192.168.1.100',
    details: 'Created a new tax credit for company ABC',
  },
  {
    id: '2',
    date: new Date('2023-10-24T11:15:43'),
    userName: 'maria.silva',
    userRole: 'Analyst',
    action: 'update',
    resourceName: 'Tax Credit',
    resourceId: 'TC-002',
    ipAddress: '192.168.1.101',
    details: 'Updated credit amount from R$ 5,000 to R$ 6,500',
  },
  {
    id: '3',
    date: new Date('2023-10-23T09:45:21'),
    userName: 'joao.santos',
    userRole: 'Manager',
    action: 'status_change',
    resourceName: 'Tax Credit',
    resourceId: 'TC-003',
    ipAddress: '192.168.1.102',
    details: 'Changed status from "Pending" to "Approved"',
    previousStatus: 'PENDING',
    newStatus: 'APPROVED'
  },
  {
    id: '4',
    date: new Date('2023-10-22T16:20:05'),
    userName: 'admin',
    userRole: 'Administrator',
    action: 'delete',
    resourceName: 'Tax Credit',
    resourceId: 'TC-004',
    ipAddress: '192.168.1.100',
    details: 'Deleted duplicated tax credit entry',
  },
  {
    id: '5',
    date: new Date('2023-10-21T10:30:15'),
    userName: 'carlos.oliveira',
    userRole: 'Auditor',
    action: 'calculation',
    resourceName: 'IRRF Calculation',
    resourceId: 'CALC-001',
    ipAddress: '192.168.1.103',
    details: 'Performed IRRF calculation for Q3 2023',
  },
  {
    id: '6',
    date: new Date('2023-10-20T15:45:33'),
    userName: 'ana.pereira',
    userRole: 'Analyst',
    action: 'export',
    resourceName: 'Report',
    resourceId: 'REP-001',
    ipAddress: '192.168.1.104',
    details: 'Exported monthly tax credit report to Excel',
  },
  {
    id: '7',
    date: new Date('2023-10-19T08:55:49'),
    userName: 'maria.silva',
    userRole: 'Analyst',
    action: 'import',
    resourceName: 'Client Data',
    resourceId: 'IMP-001',
    ipAddress: '192.168.1.101',
    details: 'Imported new client dataset from CSV file',
  }
];
